
# A unique name for the cluster that this service node/instance belongs to; use alphanumeric and underscores only.
cluster: local_default

systemDataCenter: "emodb-us-east-1"

usEast1DataCenter: "emodb-us-east-1"

euWest1DataCenter: "emodb-eu-west-1"

emoDataCenterConfiguration:
  - dataCenter: "emodb-us-east-1"
    uri: http://localhost:8080
    #uri: http://emodb.bazaar.us-east-1.nexus.bazaarvoice.com:8080
    placement: "pii_us:pii"
    locales:
      - "en_us"
  - dataCenter: "emodb-eu-west-1"
    uri: http://localhost:8090
    #uri: http://emodb.bazaar.eu-west-1.nexus.bazaarvoice.com:8080
    placement: "pii_eu:pii"
    locales:
      - "en_eu"

adminApiKey : "ADMIN-API-KEY"

# Configure the HTTP client that EmoService uses to make outbound requests.
httpClientConfiguration:
  # Timeout after 1 second while connecting.
  connectionTimeout: 1s

  # Timeout after 10 seconds while reading or writing.
  timeout: 10s

  # Keep connections open for 10 minutes.
  timeToLive: 10m

  # Don't track cookies.
  cookiesEnabled: false

  # Most responses are small and not worth compressing.  Reduce CPU.
  gzipEnabled: false
  gzipEnabledForRequests: false

  # Thread pool for JerseyClient's async requests.
  minThreads: 1
  maxThreads: 128

  # Re-use connections so we don't run out of ports if many requests are made in rapid succession.
  keepAlive: 2s


# CHECK LATER BELOW ONES ..........................................

#piiConfiguration:
#  cluster: piiproxy cluster
#  dataCenter: datacenter1
#  seeds: 127.0.0.1
#  port: 9160
#  maxConnectionsPerHost: 5
#  healthCheck:
#    name: piiproxy
#
## Configure the HTTP server that listens for inbound requests
#server:
#  applicationConnectors:
#    - type: instrumentedHttp
#      port: 8888
#  adminConnectors:
#    - type: instrumentedHttp
#      port: 8889
#
#logging:
#  level: INFO
#  appenders:
#    - type: console
#      logFormat: "%-5p [%d{ISO8601,UTC}] [%thread] %c: %m%n%xEx"
#      timeZone: UTC